# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("product.proto", :syntax => :proto3) do
    add_message "product_contract.Payload" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :category, :string, 3
      optional :price, :float, 4
      optional :quantity, :int32, 5
    end
    add_message "product_contract.CreateRequest" do
      optional :name, :string, 1
      optional :category, :string, 2
      optional :price, :float, 3
      optional :quantity, :int32, 4
    end
    add_message "product_contract.GetOrDeleteRequest" do
      optional :id, :int32, 1
    end
    add_message "product_contract.GetResponse" do
      optional :status, :message, 1, "product_contract.StatusCode"
      optional :payload, :message, 2, "product_contract.Payload"
    end
    add_message "product_contract.ListResponse" do
      optional :status, :message, 1, "product_contract.StatusCode"
      repeated :payload, :message, 2, "product_contract.Payload"
    end
    add_message "product_contract.CreateResponse" do
      optional :status, :message, 1, "product_contract.StatusCode"
      optional :id, :int32, 2
    end
    add_message "product_contract.DeleteResponse" do
      optional :status, :message, 1, "product_contract.StatusCode"
    end
    add_message "product_contract.StatusCode" do
      optional :code, :int32, 1
    end
    add_message "product_contract.Empty" do
    end
  end
end

module ProductContract
  Payload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.Payload").msgclass
  CreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.CreateRequest").msgclass
  GetOrDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.GetOrDeleteRequest").msgclass
  GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.GetResponse").msgclass
  ListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.ListResponse").msgclass
  CreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.CreateResponse").msgclass
  DeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.DeleteResponse").msgclass
  StatusCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.StatusCode").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("product_contract.Empty").msgclass
end
