# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: product.proto for package 'product_contract'

require 'grpc'
require 'product_pb'

module ProductContract
  module Actions
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'product_contract.Actions'

      rpc :CreateProduct, ::ProductContract::CreateRequest, ::ProductContract::CreateResponse
      rpc :GetProduct, ::ProductContract::GetOrDeleteRequest, ::ProductContract::GetResponse
      rpc :ListProducts, ::ProductContract::Empty, ::ProductContract::ListResponse
      rpc :DeleteProduct, ::ProductContract::GetOrDeleteRequest, ::ProductContract::DeleteResponse
    end

    Stub = Service.rpc_stub_class
  end
end
